### ISSUE TITLE
Support for custom themes

### ISSUE THREAD

**Issue by aarhusgregersen** [andrewnicols/moodle-local_usertours#26]
Currently the plugin does not support my custom theme, even though I (maybe wrongly) thought the plugin is self-sufficient.

I currently cannot display the 'navigation' part of the plugin, meaning that I can highlight and show elements correctly using either blocks or css selectors, but the navigation pad does not appear.
I tried with a different theme in which it is working.

Is the theme supposed to support the plugin in one way or another? Perhaps with certain css rules?

[See an image here](https://moodle.org/mod/forum/discuss.php?d=340152)

**Comment by andrewnicols** [comment]
Hi @gregersen12,

Thanks for raising this.

The plugin currently only supports themes which are based upon the bootstrapbase theme in Moodle.

However, the next release will ship with a complete overhaul of the underlying Javascript libraries, which means that it should now be completely theme independent.

I was hoping to have this release out the door by the end of September, but due to time constraints it's unlikely that the September release will land until early October.

I should have the updated branch with the new libraries tomorrow afternoon for my internal testing. I'll write a note on this issue when that happens in case you'd like to try it on your testing systems and provide any feedback.

Andrew

**Comment by aarhusgregersen** [comment]
Hello @andrewnicols ,

Thats perfect. I can wait a bit longer; I honestly thought the full support was already implemented but I am somewhat glad to hear it isn't; meaning I didn't F anyhing up with our theme build (well I still might have). 

I will keep a close tab on future updates.

Thanks!
